name: "Deploy Website"

concurrency:
  group: deploy-website-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
    paths:
      - 'website/public/data.json'
    tags:
      - "kaizen-website/v*.*.*"

permissions:
  contents: read
  deployments: write
  id-token: write

defaults:
  run:
    shell: bash
    working-directory: website/

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: ğŸ›¡ï¸ Harden the runner
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - name: ğŸ“¦ Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          fetch-depth: 1

      - name: ğŸ‡³ Setup Node.js
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
        with:
          node-version: "22.19.0"

      - name: âš’ï¸ Instal pnpm
        run: npm install -g pnpm

      - name: ğŸ” Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: ğŸ’¾ Cache pnpm store
        uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/website/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-pnpm-store-

      - name: âš’ï¸ Setup just
        uses: extractions/setup-just@e33e0265a09d6d736e2ee1e0eb685ef1de4669ff # v3
        with:
          just-version: "1.40.0"            

      - name: âš™ï¸ Install dependencies
        run: just ci
      
      - name: ğŸ—ï¸ Build production output
        run: just build
      
      - name:  ğŸš€ Deploy to Cloudflare Pages
        id: deploy
        uses: cloudflare/wrangler-action@da0e0dfe58b7a431659754fdf3f186c529afbe65 # v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          command: pages deploy website/dist/website --project-name=kaizen-website --branch=main --commit-hash=${{ github.sha }} --commit-dirty=true
      
      - name: ğŸ” Log Deployment URLs
        run: |
          echo "Deployment URL: ${{ steps.deploy.outputs.deployment-url }}"
          echo "Deployment Alias: ${{ steps.deploy.outputs.pages-deployment-alias-url }}"
          echo "Deployment ID: ${{ steps.deploy.outputs.command-output }}"
